name: DomesticMouse
favicon: null
layout_spectrum: 0.09932751557789743
typography_spectrum: 0.19757524551823735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8207050522323698
  lightness: 0.7066176710650325
  saturation: 0.8067691833712161
  rhythmicContrast: 0.6550046596676111
purpose: []
